- name: Set up firewall
  ansible.builtin.import_tasks: firewall.yml

- name: Set up time
  ansible.builtin.import_tasks: time.yml

- name: Set up directories and files
  ansible.builtin.import_tasks: files.yml

- name: Configure and update apt
  ansible.builtin.import_tasks: apt.yml

- name: Set up Python virtual environment
  ansible.builtin.import_tasks: python.yml

- name: Install docker
  ansible.builtin.import_tasks: docker.yml
